# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

variables:
  IMAGE_NAME: parkourben99/android-build-environment

latest:
  stage: build
  script:
    - export IMAGE_TAG=$(echo -en $CI_BUILD_REF_NAME | tr -c '[:alnum:]_.-' '-')
    - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
    - docker build --pull -t "$IMAGE_NAME:latest" .
    - docker push "$IMAGE_NAME:latest"
  only:
    - master

tagged:
  stage: build
  script:
    - export IMAGE_TAG=$(echo -en $CI_BUILD_TAG | tr -c '[:alnum:]_.-' '-')
    - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
    - docker build --pull -t "$IMAGE_NAME:$IMAGE_TAG" .
    - docker push "$IMAGE_NAME:$IMAGE_TAG"
  only:
    - tags